### ISSUE TITLE
Feature: Add support for unmanaged resources

### ISSUE THREAD

**Issue by AndreiAkhrymenko** [Azure/azure-service-operator#3095] opened 2023-06-20 15:55 UTC
I could not find a method to create resources in a Resource Group that was not created by Azure Service Operator (ASO) and is not managed by it. For instance, I would like to create some resources in an AKS Resource Group without having ASO manage the Resource Group. This is to prevent unintended deletion of the Resource Group, which may occur if I uninstall the Helm chart, for example.
No way/example to make resource group - Unmanaged.

**Comment by matthchr** [comment] 2023-06-20 15:58
I believe this is a duplicate of #2357

Take a look at the comment [here](https://github.com/Azure/azure-service-operator/issues/2357#issuecomment-1535234659), which describes the workaround as well.

**Comment by matthchr** [comment] 2023-06-20 15:59
I'm closing this on the basis I believe it's a duplicate, but if you disagree please reply.

**Closed by matthchr** 2023-06-20 15:59 UTC
Labels: new-feature
