### ISSUE TITLE
Add the capability to assign a Managed Identity to a SQL role for a newly created SQL Database

### ISSUE THREAD

**Issue by kmitawojciech** [Azure/azure-service-operator#3999] opened 2024-05-07 08:38 UTC
<Describe the feature request>

I would like to create a new instance of Azure SQL Database but I would like to be able to define the AD user (workload identity) which is granted to the created database. This would avoid specifying any kind of credentials and it would make it very convenient in case I am setting up a service which requires a Database and I would pass just the managed identity of the service to the ASO operator which would automatically grant to a specific role.

Currently there is the sql.azure.com/v1 User resource which may be assigned to a database by the operator but it is not working with AD user (the documentation is saying it works)

**Comment by matthchr** [comment] 2024-05-13 23:17
I believe that this is a duplicate of #3700. Closing - discussion can move over to that issue ideally.

**Closed by matthchr** 2024-05-13 23:17 UTC
Labels: new-feature
