### ISSUE TITLE
Bug: ResourceGroup deployed with invalid name becomes undeletable

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#2478] opened 2022-08-31 01:22 UTC
v2.0.0-beta.2

**Describe the bug**
I accidentally tried to deploy a resource group with `azureName` set to `map[create:true name:]` while working on a helm chart. The resource became undeletable, as it kept trying to delete the invalid resource group name when trying to resolve the deletion.

```
controllers/controller/resourcegroup "msg"="Reconciler error" "error"="deleting resource \"/subscriptions/{sub}/resourceGroups/map[create:true name:]\": DELETE https://management.azure.com/subscriptions/{sub}/resourceGroups/map[create:true name:]
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: InvalidResourceGroup
--------------------------------------------------------------------------------
```

**To Reproduce**
Deploy the following:
```
apiVersion: resources.azure.com/v1beta20200601
kind: ResourceGroup
metadata:
  name: my-rg
spec:
  azureName: "map[create:true name:]"
  location: westus3
```

**Expected behavior**
The original failure would have left the resource undeployed, and the reconciliation of the deletion (or edit) of the resource would not try to delete the invalidly-named original resource.

**Comment by matthchr** [comment] 2022-09-01 18:43
We've talked about making this experience better in the past (see #1273). The problem is that we also need to be fault tolerant and not ever miss deleting a resource we've created, even if the operator crashes right after sending the initial request to Azure.

Right now, the best way out is to set [skip-reconcile: detatch-on-delete](https://github.com/Azure/azure-service-operator/issues/1273) on the resource that is stuck, which will allow it to delete.

**Comment by matthchr** [comment] 2022-11-22 17:27
Closing this in favor of a more generic issue that describes this problem, as it applies to all resources: #2607

**Closed by matthchr** 2022-11-22 17:27 UTC
Labels: bug
