### ISSUE TITLE
Bug: RoleAssignments cannot be updated

### ISSUE THREAD

**Issue by dsempi** [Azure/azure-service-operator#4206] opened 2024-08-22 13:36 UTC
**Version of Azure Service Operator**

2.8.0
`azureserviceoperator-controller-manager   1/1     1            1           15d   manager      mcr.microsoft.com/k8s/azureserviceoperator:v2.8.0   control-plane=controller-manager`

**Describe the bug**

When the principle ID is changed in authorization.azure.com/v1api20200801preview RoleAssignment spec, the RoleAssignment object runs into an error like:
```
Tenant ID, application ID, principal ID, and scope are not allowed to be updated.: PUT https://management.azure.com/subscriptions/<subscription id>/resourceGroups/<resource group name>/providers/Microsoft.ServiceBus/namespaces/<service bus namespace>/providers/Microsoft.Authorization/roleAssignments/<role assignement id>
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: RoleAssignmentUpdateNotPermitted
-------------------------------------------------------------------------------- 
{
  "error": {
   "code": "RoleAssignmentUpdateNotPermitted",
   "message": "Tenant ID, application ID, principal ID, and scope are not allowed to be updated."
  }
}    
```                    

**To Reproduce**
1. Create a role assignment
2. Wait until it's reconciled
3. Change the principal ID
4. During the reconciliation, the object runs into an error 

**Expected behavior**
Since the PUT operation for role assignments does not allow changes in Azure, the operator should rather recreate (DELETE and PUT) the role assignment if changes are detected to fulfill the Kubernetes desired state principle.

**Comment by matthchr** [comment] 2024-08-26 23:29
This is a duplicate of #3318 it looks like. This isn't really a _bug_ per-se, ASO today doesn't ever automatically delete anything in Azure. The reason for that behavior is the reality that some resources can cause major downtime when deleted and recreated.

With that said, as mentioned in #3318, we may want some sort of configuration (annotation? operatorSpec property?) to control this behavior and allow users to opt-in to it on resources they want it for.

**Closed by matthchr** 2024-08-26 23:29 UTC
Labels: bug 🪲, needs-triage :mag:
