### ISSUE TITLE
Bug: using azure service operator deploy PostgreSQL flexible servers encounter error in azure "Number of write requests for subscription xxx exceeded the limit of '1200' for time interval '01:00:00'. Please try again after xx seconds"

### ISSUE THREAD

**Issue by Gan-Jun** [Azure/azure-service-operator#2643] opened 2022-12-05 10:14 UTC
**Version of Azure Service Operator**
aso/azure_service_operator:v2.0.0-beta.2, kubebuilder/kube-rbac-proxy:v0.13.0

**Describe the bug**
  We are planning to migrate our project platform from azure ChinaNorth2 region to ChinaNorth3 region so that we can switch from postgresql singleserver to postgresql flexibleserver. there are 40~50 postgresql flexibleservers to be created in ChinaNorth3 region by using azure_service_operator:v2.0.0-beta.2.
  While testing postgresql flexibleservers deployment in lower stage environment, we see there are many "**Write FirewallRules, Write Configurations, Write Databases**" requests in activity log in azure portal, those too frequent write request caused error: **Number of write requests for subscription 'xxx' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '303' seconds**. 
  Even for successfully created postgresql flexibleserver, still azure service operator sends "**Write FirewallRules, Write Configurations, Write Databases**" requests to azure.  and in values.yaml for azure service operator deployment, I am using default setting of **azureSyncPeriod: "", azureOperatorMode: ""**, but not sure why it still sends these write requests frequently.

**To Reproduce**
screenshot of settings and log:
1. values.yaml file for azure_service_operator:v2.0.0-beta.2 deployment using helm3 in azure kubernates:
![valuesyaml](https://user-images.githubusercontent.com/48749989/205610784-fc3b16eb-a038-4a55-80f1-fcf11af15c00.png)
2. use concourse pipeline job to deploy azure_service_operator and override some default settings in values.yaml file:
![concourse-job](https://user-images.githubusercontent.com/48749989/205610828-6f435136-5d74-403b-8f16-aefabb12304e.png)
3. template file for postgresql flexibleserver:
![psql-template](https://user-images.githubusercontent.com/48749989/205610863-b6ffdc88-52e2-49cf-a111-2b1f2b2c8649.png)
4. too many "**Write FirewallRules, Write Configurations, Write Databases**" requests in activity log in azure portal:
![write requests log](https://user-images.githubusercontent.com/48749989/205610938-75b46666-3a79-4c11-b66e-416df48675a9.png)

**Expected behavior**
azure_service_operator should not send "Write FirewallRules, Write Configurations, Write Databases" requests to azure after postgresql flexibleserver deployment is done, to avoid the limit of '1200' for time interval '01:00:00'

**Comment by theunrepentantgeek** [comment] 2022-12-06 21:55
A successful PUT of a PostgreSQL Flexible server does not indicate that the deployment of that server has completed. It indicates that the deployment has begun. It's our experience that deployment of a PostgreSQL Flexible Server can take up to 45 minutes.

With this in mind, what appears to be happening is that ASO thinks the server is ready to go and is trying (and failing) to create the firewall rules and other configuration specified in your YAML file.

In our testing, we deploy both firewall rules and configuration items for a single server, and we don't come close to triggering ARM throttling.

You mention
> there are 40~50 postgresql flexibleservers to be created

**How many servers are you deploying at one time?**

**Immediate mitigation**
The `skipreconcile` annotation allows you to stop ASO from trying to reconcile a specific resource. 
You could apply that to the firewall and configuration resources, removing it only once provisioning of the server itself is complete.

I understand that this is suboptimal, but it's a way forward you can apply today, without waiting for our next release.

**Short term improvements**
In the upcoming `beta.4` release (due in the next couple of weeks), we have a number of changes to reduce the number of ARM PUT calls it makes, reducing (but not eliminating) the likelihood of triggering ARM throttling.

* #2582 changes our retry behaviour to retry less often if/when an error is returned from ARM. 
* #2601 changes our internal rate limiter to closely match the usual ARM limits.

**Long term improvements**
* #2644 tracks our design work for an extension point to allow us to customize the reconciliation behaviour for each resource type. This will allow us to better detect that a PostgreSQL Flexible Server isn't yet ready, deferringg attempts to reconcile child resources.
* #2600 tracks our design work to switch from PUT only to doing a GET then a PUT for each resource; this will allow us to only do a PUT when necessary (ARM throttle limits for GETs are much higher than for PUTs)

**Further improvements**
@super-harsh is going to try and reproduce your issues so that we better understand what's going on. This may allow us to provide additional workarounds.

**Other information**
The configuration value for `azureSyncPeriod` impacts on how often ASO will reconcile a resource after it is successfully created. Setting this to an empty string ("") doesn't turn off initial reconciliations, nor does it turn off retries while ASO tries to bring the resource to the desired goal state.

Setting `azureOperatorMode` to empty string is the same as specifying `both`, which is the default value.

**Comment by Gan-Jun** [comment] 2022-12-07 06:43
we have deployed around 40 flexible servers thru concourse pipeline which was triggered manually, and these servers are deployed at around 10 mins interval between each other. Today morning(11:45 UTC+8) I can see all the servers have been created successfully by azure service operator. 
![ready](https://user-images.githubusercontent.com/48749989/206103774-61292c91-6129-4e28-9e01-a52c64fb17fd.png)

But still I can see there are many Write request in azure activity log after the timepoint that flexibleserver related resource status shown as Succeeded in Kubernetes. 
![activitylog](https://user-images.githubusercontent.com/48749989/206104222-a0373c5d-985f-4c14-9506-f29c29eb391f.png)

The write requests(12:06 UTC+8) caused **flexibleserversconfigurations.dbforpostgresql.azure.com** resource status changed from **Succeeded** to **SubscriptionRequestsThrottled** again.
![notready](https://user-images.githubusercontent.com/48749989/206104664-3345b159-dcb2-4889-b010-0af54a106daf.png)
**The expected behavior:** "No write request be sent to azure after all resources' status shown as Succeeded". Is it because there are many write requests blocked and waiting in the queue after reaches ARM throttling, and after waiting for some time, ARM throttling not reached, these pending write request is processed by azure again?
**One more thing:** after flexibleserver is provisioned by azure service operator, if I manually update the flexibleserver or serverconfiguration setting in azure portal(i.e. change HA setting from Disabled to Samezone HA as currently azure china only support samezone HA but azureserviceoperator v2.0.0-beta.2 don't support Samezone HA), will this manual change be overwritten/lost by azure service operator?

**Comment by theunrepentantgeek** [comment] 2022-12-07 22:00
> The expected behavior: "No write request be sent to azure after all resources' status shown as Succeeded"

This is not expected behaviour for any Kubernetes operator. The resource specification in the cluster defines the desired state of the resource and ASO will work to maintain that exact configuration in Azure.

ASO will regularly reconcile each resource and will change it back to the spec given by the cluster if it gets modified.

You _can_ effectively turn this off by setting `azureSyncPeriod` to a very long period (years), but this is disabling the primary function that ASO is designed to deliver. It's also risky - if the resource is modified in the cluster, or if the ASO pod is restarted, a reconcile will occur and the configuration pushed to Azure.

> Is it because there are many write requests blocked and waiting in the queue after reaches ARM throttling, and after waiting for some time, ARM throttling not reached, these pending write request is processed by azure again?

No. Write requests rejected by ARM due to throttling are not retained. The writes you see are ASO correctly reconciling the resource, ensuring that it remains as specified.

> after flexibleserver is provisioned by azure service operator, if I manually update the flexibleserver or serverconfiguration setting in azure portal ... will this manual change be overwritten/lost by azure service operator?

Yes, it will be overwritten. ASO treats the resource definition in the cluster as the one source of truth and will attempt to modify the resource in Azure to conform.

> we have deployed around 40 flexible servers

If we do a back-of-the-envelope calculation and assume each server has 5 firewall rules and 5 configurations, we end up with 11 resources per server. 
For 40 servers, this comes to 440 resources. 
Reconciling these 4 times per hour (every 15m) would require 1760 PUT requests, well exceeding the normal ARM limit of 1200 PUT requests per hour.

In our upcoming `beta.4` release we're changing the default to 60m, but you don't have to wait for that. Changing `azureSyncPeriod` should allow you to avoid throttling with your current installation. You may need to adjust this to reflect your actual resource count (e.g. if you want to scale to 80 or 100 servers, you'll need a longer reconcile period).

**Comment by Gan-Jun** [comment] 2022-12-08 05:05
- Does the default setting `azureSyncPeriod: ""` can turn off resource reconcile? or resource reconcile only can be turned off by setting azureSyncPeriod to a very long period (years)?

- What's the azureSyncPeriod calculation logic? i.e. azureSyncPeriod set to 30days, and aso Pod is running for 10 days, then I manually restart ASO Pod, will the azure sync operation happen after 20days or 30days? 
The purpose is to avoid azureSync operation happens on daytime in Production environment. Once azureSync time is coming we will manually restart ASO Pod at nighttime in advance (based on your above reply, after ASO pod restart, reconcile will occur as well).

**Comment by theunrepentantgeek** [comment] 2022-12-10 03:23
> Does the default setting azureSyncPeriod: "" can turn off resource reconcile?

No. Turning off reconciliation isn't supported. The closest you can get is to explicitly set it to a very long period. An empty string (`""`) is the same as the default: 15m in current releases; 60m in the upcoming `beta.4` release.

Putting throttling aside, why do you want to disable reconciliation? If the resource is in the goal state you've defined in the cluster, the ARM PUT will be a null-operation that has no effect. If the resource is _**not**_ in the goal state you've defined in the cluster, wouldn't you want it restored to the correct condition?

If what you want is a fire-and-forget deployment tool, then I'd suggest that ASO probably isn't the tool you want. ASO is designed to actively manage your Azure resources, allowing you to define a custom resource in your cluster that is reflected through into Azure with goal-seeking behaviour.

Put another way, the monitoring and goal-seeking behaviour intrinsic to ASO is one of the central value-adds that it brings; if all you want is a simple deployment tool, ARM or Bicep are likely to be a better fit.

> What's the azureSyncPeriod calculation logic?

It's an internal (in memory) timer used within the ASO pod. It's not based on any external references. Restarting the pod will trigger an immediate reconciliation of all supported resources.

> azureSyncPeriod set to 30days, and aso Pod is running for 10 days, then I manually restart ASO Pod, will the azure sync operation happen after 20days or 30days?

Neither. Reconciliation will happen immediately following the pod restart. If your resources are already in the desired final state, reconciliation will not change them.

> If add skipreconcile: "true" annotation to flexibleserver related resources after flexibleserver is provisioned, delete ASO related CRDs or delete K8s cluster will not impact the flexibleserver in Azure(flexibleserver won't be deleted), am I right?

I've been corrected by a colleague - the annotation to apply is `serviceoperator.azure.com/reconcile-policy: skip`.

The behaviour of the annotations is documented on our [Annotations understood by the operator ](https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy) page.

If `serviceoperator.azure.com/reconcile-policy` is set to either `skip` or `detach-on-delete` then the Azure resource will be untouched if/when you delete the resource from the cluster.

**Comment by Gan-Jun** [comment] 2022-12-12 07:27
Thanks for your explanation. `serviceoperator.azure.com/reconcile-policy: skip` annotation works fine during my testing.

We are switching from azure postgresql singleserver (created via ASO v1) to azure postgresql flexibleserver, use ASO v2 we can reuse the existing pipeline code (only with some adjustment) for application and db server deployment. 

After DB server is provisioned by ASO in PROD environment, I think there will be no change to the server in the future, so it's better to add reconcile-policy annotation to avoid PUT request be sent to azure, and no need to worry about the setting of azureSyncPeriod.

**Comment by theunrepentantgeek** [comment] 2022-12-12 21:41
You may want to keep an eye on #1491, which is on our longer-term roadmap. Once that lands, we'll only be issuing PUTs when there are changes that need to be applied.

Are you happy for me to close this issue?

**Closed** 2022-12-14 07:29 UTC
Labels: bug
