### ISSUE TITLE
PostgreSQLUser- secret can be only deployed in the same namespace as PostgresSQLServer

### ISSUE THREAD

**Issue by EdYa** [Azure/azure-service-operator#1396] opened 2021-03-19 09:08 UTC
**Describe the bug**
I need to deploy PostgreSQLUser to the same namespace as PostgreSQL Server. Otherwise the secret for the creation of the user can't be found. Afterwards the secret is also created in the same namespace. But this shouldn't be the case. The secret is needed in the namespace of the PostgreSQLDatabase because the user should be database and not server specific. Background of our setup: we have on PostgreSQLserver and would like to provision multiple databases in different namespaces on it. 

**To Reproduce**
- Create PostgreSQLServer, PostgreSQLUser and PostgreSQLFirewallRule in the default namespace. ( It is  not possible to create the PostgreSQL-User in a different namespace the the PostgreSQLServer - otherwise the user can't be provisioned)
- Create PostgreSQLDatabase in a custom namespace

**Expected behavior**
The PostgreSQLUser-secret is created in the custom namespace. 

**Screenshots**

**Additional context**

**Comment by matthchr** [comment] 2021-03-22 23:49
I believe that the secret for a user and the user itself always need to be in the same namespace for security (and ownership) reasons. 

Ownership requires the same namespace because Kubernetes doesn't allow cross namespace ownership references and the secret needs to be owned by the resource creating it (that way it gets deleted if the resource gets deleted).
Security requires the same namespace because it would be very easy to give away access to a different namespace than the one the user is in and unwittingly allow somebody to access the user. The user and its secret are two parts of the same logical entity and should be located together in Kubernetes.

An alternative way to achieve what you're asking for would be to allow the creation of a `PostgreSQLServerAdministrator` resource which could delegate permissions to be the server admin to the Managed Identity that the operator is running as. Then the operator could create the user in any namespace because it doesn't need access to the server admin secret. We support this for `MySQL` fully today, and partially for `AzureSQL`, so allowing that would be following a similar pattern.

I also want to mention that longer term we want to discourage cross-namespace references as they mean that we cannot use Kubernetes ownership to tie the resources together. Today if you create a Server, DB, and User all in the same namespace, then when you delete the server, the DB and User will be deleted. If you create the Server in one namespace and the DB in another and then if you delete the Server the DB will stick around and throw a bunch of errors as it fails to reconcile. We may introduce concepts in the future to help mitigate this problem as well.

If you agree that the AAD Server Administrator + Managed Identity approach allowing the user to be created in a different namespace than the server would solve your problem, I can edit this issue to be a feature request for that. See #1353 for a related issue talking about this problem.

**Comment by EdYa** [comment] 2021-03-23 16:13
I could imagine that this feature could be quite helpful. On the other hand we are not using a managed identity but a service principal at the moment. 
I could imagine that annotation support for secrets could be quite helpful. If we could add some annotations for kubernetes-reflector then we could mirror the secrets to the correct namespace.

**Comment by matthchr** [comment] 2021-03-25 18:09
> If we could add some annotations for kubernetes-reflector then we could mirror the secrets to the correct namespace.

That seems like a reasonable ask to me. If ASO is going to be creating a secret for a particular CRD then maybe there needs to be a `secretConfiguration` section of the CRD that allows you to some control over the secret that is created. For example for `PostgreSQLUser` you could have:

```
apiVersion: azure.microsoft.com/v1alpha1
kind: PostgreSQLUser
metadata:
  name: psqluser
spec:
  server: psqlserver
  dbName: psqldb
  resourceGroup: myrg
  secretConfig:
    metadata:
      annotations:
        my-annotation: "foo"
```

Then there would be two ways to achieve the scenario you were looking for:
1. Use managed identity for ASO. Deploy `PostgreSQLServer` into `ns1`. Configured the managed identity of ASO as AAD admin of the `PostgreSQLServer`. Deploy `PostgreSQLDB` into `ns1` or `ns2`. Deploy `PostgreSQLUser` into `ns2`.
2. Use service principal for ASO. Deploy `PostgreSQLServer` into `ns1`. Deploy `PostgreSQLDB` into `ns1`. Deploy `PostgreSQLuser` into `ns1`, with `secretConfig` annotation to be used by kuberentes-reflector to reflect secret to desired namespace.

Would one of those patterns work for you?

**Comment by EdYa** [comment] 2021-03-26 10:10
Yes I think so

**Comment by matthchr** [comment] 2021-03-26 23:59
@EdYa I've filed two new feature requests (#1398 and #1399) that represent the two cases I mentioned above. Closing this in favor of those.

**Closed by matthchr** 2021-03-26 23:59 UTC
Labels: bug

**Comment by fredgate** [comment] 2021-04-07 18:53
This issue is closed, but I have similar needs for Mysql. Also @matthchr I have some questions for you.

Here is my scenario : as a cluster administrator I would like to create a Mysql Server in a reserved namespace. Then I would like that developers to be able to create Mysql databases on this server from their dedicated namespaces.  
The `MysqlServer` resource should be in a namespace `ns1` (with the admin secret ?). Then the `MysqlDatabase` resources should be in the namespaces dedicated to the different developers : `ns2`, `ns3`...

I read the whole thread but i don't see how to achieve this. I am open to any solution and also have questions about what has been said before.

First could you explain why the operator needs that the `MysqlUser` resources be in the same namespace as the `MysqlServer` resource ? Why when it creates an user defined in a namespace `ns2`, it can not read a secret in a namespace `ns1` ? 

> An alternative way to achieve what you're asking for would be to allow the creation of a `PostgreSQLServerAdministrator` resource which could delegate permissions to be the server admin to the Managed Identity that the operator is running as. Then the operator could create the user in any namespace because it doesn't need access to the server admin secret. We support this for `MySQL` fully today, and partially for `AzureSQL`, so allowing that would be following a similar pattern.

How works the `MySQLServerAdministrator` resource and how to use it ? I did not find any documentation about this CRD.

> Then there would be two ways to achieve the scenario you were looking for:
> 1. Use managed identity for ASO. Deploy PostgreSQLServer into ns1. Configured the managed identity of ASO as AAD admin of the PostgreSQLServer. Deploy PostgreSQLDB into ns1 or ns2. Deploy PostgreSQLUser into ns2.

How to do `Configured the managed identity of ASO as AAD admin of the PostgreSQLServer` ? If this is a manual operation using Azure portal or az CLI, then Azure Service Operator loses some of his interest.

**Comment by matthchr** [comment] 2021-04-08 20:52
> Here is my scenario : as a cluster administrator I would like to create a Mysql Server in a reserved namespace. Then I would like that developers to be able to create Mysql databases on this server from their dedicated namespaces.

If there are no users involved, then there's no issue there. Creating `MySQLServer` and `MySQLDatabase` are both Azure ARM operations that can be done with the service principal or managed identity ASO is deployed with, so they can be done from any namespace. If that's all you need to do you can ignore everything I've typed below.

> First could you explain why the operator needs that the MysqlUser resources be in the same namespace as the MysqlServer resource ? Why when it creates an user defined in a namespace ns2, it can not read a secret in a namespace ns1 ?

In theory, it could. We could add a field on the `MySQLUser` that said what namespace to read the secret from and then try to read it. The problem is that this kind of ends up bypassing standard Kubernetes RBAC. With such an option there would be no way to prevent any user on any cluster in any namespace from guessing the name of the secret in the given namespace and creating users on the DB. There are lots of scenarios where that's not good. The pattern of "just read the thing from the other namespace on my behalf" is a pattern that is concerning from a security perspective because the operator is deployed globally and has pretty broad permissions.

> How works the MySQLServerAdministrator resource and how to use it ? I did not find any documentation about this CRD.

Oops! filed #1404 for the poor documentation.
`MySQLServerAdministrator` is a way to assign an AAD identity as an administrator of the `MySQL` server. The normal workflow would be:
1. Configure ASO with Managed Identity
2. Create `MySQLServer`
3. Create `MySQLServerAdministrator` with the same Managed Identity ASO is deployed with. This is you effectively saying "I want ASO to administer my server". You can look at https://github.com/Azure/azure-service-operator/blob/master/config/samples/azure_v1alpha1_mysqlserveradministrator.yaml to see how to do that.
4. Create users from whatever namespace you want (see #1353 for some limitations of this today).

> How to do Configured the managed identity of ASO as AAD admin of the PostgreSQLServer ? If this is a manual operation using Azure portal or az CLI, then Azure Service Operator loses some of his interest.

It's not manual, you can do it with a CRD we support. There are some limitations of it today (#1353 and #1401).


Can you tell me a bit more about your scenario and its requirements? Why not just make the whole set of DBs in the same namespace? If you want to deny users the ability to delete the server then you can do that with Kubernetes RBAC and still allow them the ability to create DBs in that namespace?
