### ISSUE TITLE
Bug: 'serviceoperator.azure.com/reconcile-policy: detach-on-delete' annotation overwrites existing KeyVault access policies 

### ISSUE THREAD

**Issue by mehighlow** [Azure/azure-service-operator#2574] opened 2022-11-01 07:00 UTC
**Version of Azure Service Operator**
mcr.microsoft.com/k8s/azureserviceoperator:v2.0.0-beta.3

**Describe the bug**
Creation of a Vault object with `serviceoperator.azure.com/reconcile-policy: detach-on-delete` annotation overwrite all existing policies.

**To Reproduce**
1. Manually create an Azure KeyVault
2. Manually create an access policy
3. Create a Vault object with `serviceoperator.azure.com/reconcile-policy: detach-on-delete` annotation

```yaml
apiVersion: keyvault.azure.com/v1beta20210401preview
kind: Vault
metadata:
  name: webcluster-secrets
  namespace: default
  annotations:
    serviceoperator.azure.com/reconcile-policy: detach-on-delete # https://azure.github.io/azure-service-operator/introduction/annotations/#serviceoperatorazurecomreconcile-policy
spec:
  location: eastus
  owner:
    name: rg-name
  properties:
    tenantId: "00000000-0000-0000-0000-000000000000"
    sku:
      family: A
      name: standard
    accessPolicies:
      - applicationId: "00000000-0000-0000-0000-000000000000" # MI ClientID
        objectId: "00000000-0000-0000-0000-000000000000" # MI ObjectID
        tenantId: "00000000-0000-0000-0000-000000000000"
        permissions:
          certificates:
            - "get"
          keys:
            - "get"
          secrets:
            - "get"
          storage:
            - "get"
```
4. Check the KeyVault policies. Previously manually created policy has been overwritten

**Expected behavior**
ASOv2 append policies to the existing ones. On delete ASOv2 deletes policies created by itself.

**Screenshots**
N/A

**Additional context**

**Comment by matthchr** [comment] 2022-11-01 20:45
This is currently expected behavior.

* `detach-on-delete` instructs ASO that it is allowed to update the resource in question (in this case a `Microsoft.KeyVault/vault`).
* The `accessPolicies` property in the the `Vault` is replaced entirely each time ASO reconciles the resource (PUT not PATCH). Basically ASO assumes control over the entire shape of the object. This is required for the ability to do things like remove `accessPolicies`.

This means that you need to have ASO manage all of the accessPolicies on your KeyVault, or none of them. If you want it to manage none of them you can use `reconcile-policy: skip`. Otherwise it owns all of them.

**Comment by matthchr** [comment] 2022-11-01 20:49
Closing this as by design, but feel free to comment or reopen if you think there's further discussion.

**Closed by matthchr** 2022-11-01 20:49 UTC
Labels: bug, needs-triage :mag:
