### ISSUE TITLE
Bug: properties.count is missing when creating auto scaling agent pool

### ISSUE THREAD

**Issue by b1zzu** [Azure/azure-service-operator#3220] opened 2023-08-31 10:14 UTC
**Version of Azure Service Operator**
`mcr.microsoft.com/k8s/azureserviceoperator:v2.2.0`

**Describe the bug**
I'm trying to create the following managed cluster agent pool:
```
apiVersion: containerservice.azure.com/v1api20230201
kind: ManagedClustersAgentPool
metadata:
  name: highmem
  namespace: default
  annotations:
    serviceoperator.azure.com/reconcile-policy: detach-on-delete
spec:
  azureName: highmem0
  owner:
    name: my-cluster
  mode: User
  enableAutoScaling: true
  minCount: 3
  maxCount: 21
  upgradeSettings:
    maxSurge: 33%
  vmSize: Standard_E2s_v4
```

but the reconciliation loops fails with the following error:

```
--------------------------------------------------------------------------------                                                                                                  
RESPONSE 400: 400 Bad Request                                                                                                                                                     
ERROR CODE: InvalidParameter                                                                                                                                                      
--------------------------------------------------------------------------------                                                                                                  
{                                                                                                                                                                                 
  "code": "InvalidParameter",                                                                                                                                                     
  "details": null,                                                                                                                                                                
  "message": "Required parameter properties.count is missing (null).",                                                                                                            
  "subcode": "",                                                                                                                                                                  
  "target": "properties.count"                                                                                                                                                    
}                                                                                                                                                                                 
-------------------------------------------------------------------------------- 
```

on `PUT https://management.azure.com/subscriptions/my-sub-id/resourceGroups/my-group/providers/Microsoft.ContainerService/managedClusters/my-cluster/agentPools/highmem0`

**Workaround**

Add `count: 1` to the `spec`, it will be ignored because the auto-scaling settings will overwrite it but at least will fix the issue.

**Comment by matthchr** [comment] 2023-09-27 16:03
Sorry for the slow response on this @b1zzu. This looks like a bug to me as well but I am confirming with the AKS team.

**Comment by matthchr** [comment] 2023-09-29 15:21
Confirmed that this is a bug/unintended behavior in the AKS API.

In the meantime, your workaround will work. The AKS team will fix this behavior in a future release, but I don't have an ETA currently.

I'll leave this item open to track this.

**Comment by matthchr** [comment] 2024-08-05 23:26
I think that this behavior has been solved in the upstream AKS API. I will confirm when it is being released as it may not be released yet.

**Comment by matthchr** [comment] 2024-08-07 23:15
Fix for this should be rolling out in a few weeks across the whole of AKS (so will improve this experience in ASO but also ARM templates, Terraform, etc).

Going to go ahead and close this given that is happening and there's nothing for us to do on ASO side.

**Closed by matthchr** 2024-08-07 23:15 UTC
Labels: bug 🪲, known-issue, blocked 🚧
