### ISSUE TITLE
Unable to bring up service Operator.

### ISSUE THREAD

**Issue by Abhinand-Gokul** [Azure/azure-service-operator#1343] opened 2020-12-29 21:29 UTC
**Describe the bug**
I am trying to install Azure Service Operator on my local Docker-Desktop installation and I am unable to get it up and running.. Azureoperator-controller-manager fails to come up consistently with the same error. I have deleted everything, tried a fresh install; still I get the same error.

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T18:49:28Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:04:18Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
`kubectl get pod -n azureoperator-system
NAME                                                READY   STATUS             RESTARTS   AGE
azureoperator-controller-manager-6db75f56fd-h5qzp   1/2     CrashLoopBackOff   13         22m`
```
kubectl get pod -n azureoperator-system azureoperator-controller-manager-6db75f56fd-h5qzp -o jsonpath='{.metadata.namespace}'
azureoperator-system
```
```
kubectl logs -n azureoperator-system azureoperator-controller-manager-6db75f56fd-h5qzp manager
2020-12-29T21:16:09.073Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2020-12-29T21:16:09.074Z	ERROR	setup	unable to parse settings required to provision resources in Azure	{"error": "couldn't get POD_NAMESPACE env variable: could not find ENV var with POD_NAMESPACE", "errorVerbose": "could not find ENV var with POD_NAMESPACE\ncouldn't get POD_NAMESPACE env variable\ngithub.com/Azure/azure-service-operator/pkg/resourcemanager/config.ParseEnvironment\n\t/workspace/pkg/resourcemanager/config/env.go:65\nmain.main\n\t/workspace/main.go:137\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
main.main
	/workspace/main.go:139
runtime.main
	/usr/local/go/src/runtime/proc.go:203
```
**To Reproduce**
Following the installation procedure from here : https://github.com/Azure/azure-service-operator 

**Expected behavior**
controller manager comes up.

**Screenshots**

**Additional context**

**Comment by ChuckkNorris** [comment] 2021-01-06 21:31
Having the same issue when following the [Azure Service Operator docs](https://github.com/Azure/azure-service-operator).
![image](https://user-images.githubusercontent.com/7637401/103821629-d8708280-502b-11eb-96d6-757f68b87cb3.png)

**Comment by matthchr** [comment] 2021-01-08 19:45
This is a duplicate of #1327, closing this in favor of that as it has more details.

**Closed by matthchr** 2021-01-08 19:45 UTC
Labels: bug
