### ISSUE TITLE
Bug: Can't modify the app.kubernetes.io/managed-by label on CRs

### ISSUE THREAD

**Issue by b1zzu** [Azure/azure-service-operator#3148] opened 2023-07-19 08:35 UTC
**Version of Azure Service Operator**

`mcr.microsoft.com/k8s/azureserviceoperator:v2.1.0,gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1`

**Describe the bug**

I'm trying to modify the `app.kubernetes.io/managed-by` label of a `storage.azure.com/v1api20220901.StorageAccountsBlobService` resource I've previously created but it fails with the following error:

```
Error from server: failed to prune fields: failed add back owned items: failed to convert pruned object at version storage.azure.com/v1api20220901: conversion webhook for storage.azure.com/v1api20220901storage, Kind=StorageAccountsBlobService returned invalid metadata: invalid metadata of type <nil> in input object
```

**To Reproduce**

`kubectl apply ...` of:

```
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccountsBlobService
metadata:
  name: storage-account-blob-service
  namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: me
spec:
  owner:
    name: storage-account
```

than `kubectl apply ...` again changing the `app.kubernetes.io/managed-by` label

```
apiVersion: storage.azure.com/v1api20220901
kind: StorageAccountsBlobService
metadata:
  name: storage-account-blob-service
  namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: someone-else
spec:
  owner:
    name: storage-account
```

**Expected behavior**

I should be able to change the `app.kubernetes.io/managed-by` whenever I want because it identifies the tool/framework/controller I use to create and manage the CR definition.

**Comment by matthchr** [comment] 2023-07-24 23:03
Sorry for the slow response here - I am looking into this and will get back to you shortly.

**Comment by b1zzu** [comment] 2023-08-17 15:15
Hi @matthchr do you have any updates for me? I've been testing it with version 2.2.0 and I have the same error.

My workaround is to add `storage` to each resource like this:
```
apiVersion: storage.azure.com/v1api20220901storage
kind: StorageAccountsBlobService
metadata:
  name: storage-account-blob-service
  namespace: my-namespace
  labels:
    app.kubernetes.io/managed-by: someone-else
spec:
  owner:
    name: storage-account
```

**Comment by matthchr** [comment] 2023-08-18 21:53
Sorry for being slow on this @b1zzu. I'm unable to reproduce this locally on either Kubernetes 1.26 or 1.27.

I did do some searching though and the error you're getting looks possibly related to an upstream Kubernetes issue in 1.27 with server-side apply:
1. https://github.com/fluxcd/flux2/issues/3179
2. https://github.com/kubernetes/kubernetes/issues/117260

Are you using flux? What version of Kubernetes are you running? Can you try updating to the latest patch of 1.27? You've actually reproduced this by using `kubectl apply` (without `--server-side=true`), or do you only see it when submitting the CRs via Flux?

I don't _think_ this is specific to ASO, I think it's that referenced upstream issue, but more details would help.

**Comment by ashetonh-ad** [comment] 2023-09-18 13:16
I'm seeing a similar issue with updating ServerFarms after some manual intervention on the azure resource through the portal.

**Comment by matthchr** [comment] 2023-09-18 14:51
Can you share the full error you're seeing @ashetonh-ad?

**Comment by matthchr** [comment] 2023-10-02 22:33
This looks related to https://github.com/kubernetes/kubernetes/issues/117356

**Comment by matthchr** [comment] 2023-10-02 23:21
Closing this in favor of the slightly better titled #3343

**Closed by matthchr** 2023-10-02 23:21 UTC
Labels: bug 🪲, waiting-on-user-response
