### ISSUE TITLE
Bug: Handle deletion of storage with invalid RG

### ISSUE THREAD

**Issue by cnadolny** [Azure/azure-service-operator#804] opened 2020-03-24 05:58 UTC
**Describe the bug**
If you create a storage account, the error is logged properly within the status object:
```
Spec:
  Access Tier:     Hot
  Kind:            StorageV2
  Location:        westus
  Resource Group:  helm222
  Sku:
    Name:                       Standard_RAGRS
  Supports Https Traffic Only:  true
Status:
  Message:  storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'helm222' could not be found."
  State:    NotReady
Events:
  Type    Reason  Age   From                Message
  ----    ------  ----  ----                -------
  Normal  Added   9s    Storage-controller  Object finalizer is added
```

However, if you try and delete it, Kubernetes hangs, and this error is seen within the logs:
```
2020-03-23T22:54:14.785-0700	ERROR	controller-runtime.controller	Reconciler error	{"controller": "storage", "request": "default/st2111132112", "error": "1 error occurred:\n\t* storage.AccountsClient#Delete: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code=\"ResourceGroupNotFound\" Message=\"Resource group 'helm222' could not be found.\"\n\n"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/administrador/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/administrador/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/administrador/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:192
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/Users/administrador/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.2.0-beta.4/pkg/internal/controller/controller.go:171
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/administrador/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/administrador/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/administrador/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190404173353-6a84e37a896d/pkg/util/wait/wait.go:88
```

**To Reproduce**
Create a SA with invalid RG
Try to delete the SA

**Expected behavior**
Error to be handled, and resource to delete in a timely fashion from Kubernetes.

**Screenshots**

**Additional context**

**Comment by matthchr** [comment] 2020-06-19 18:09
I wasn't able to reproduce this issue - it may have already been fixed?

I created a storage account with a RG that doesn't exist:
```
NAME                      PROVISIONED   MESSAGE
storageaccountsample777                 storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'asdfasfasafsafsagdweqa12414312' could not be found."
```

I deleted that storage account:
```
~/work/github/azure-service-operator (master) $ kubectl delete storageaccount storageaccountsample777 
storageaccount.azure.microsoft.com "storageaccountsample777" deleted
```

I confirmed that account was deleted:
```
~/work/github/azure-service-operator (master) $ kubectl get storageaccount
No resources found in default namespace.
```

The controller hit no errors:
```
2020-06-19T10:43:45.195-0700    INFO    controllers.StorageAccount    reconciling object not finished    {"Info Type": "status", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:43:45.195-0700    INFO    controllers.StorageAccount    exiting reconciliation    {"Info Type": "status", "Component": "StorageAccount", "Instance": ""}
2020-06-19T10:43:45.196-0700    INFO    controllers.StorageAccount    reconciling object    {"Info Type": "status", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:43:46.086-0700    INFO    controllers.StorageAccount    reconciling object not finished    {"Info Type": "status", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:43:46.086-0700    INFO    controllers.StorageAccount    exiting reconciliation    {"Info Type": "status", "Component": "StorageAccount", "Instance": ""}
2020-06-19T10:44:05.195-0700    INFO    controllers.StorageAccount    reconciling object    {"Info Type": "status", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:44:06.009-0700    INFO    controllers.StorageAccount    reconciling object not finished    {"Info Type": "status", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:44:06.009-0700    INFO    controllers.StorageAccount    exiting reconciliation    {"Info Type": "status", "Component": "StorageAccount", "Instance": ""}
2020-06-19T10:44:10.625-0700    DEBUG    controller-runtime.manager.events    Normal    {"object": {"kind":"StorageAccount","namespace":"default","name":"storageaccountsample777","uid":"a1c7fe4c-b3bd-47ac-9152-d845e7823975","apiVersion":"azure.microsoft.com/v1alpha1","resourceVersion":"2527496"}, "reason": "Deleted", "message": "Successfully deleted"}
2020-06-19T10:44:10.639-0700    DEBUG    controller-runtime.controller    Successfully Reconciled    {"controller": "storageaccount", "request": "default/storageaccountsample777"}
2020-06-19T10:44:10.639-0700    INFO    controllers.StorageAccount    error during fetch from api server    {"Info Type": "ignorable error", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:44:10.639-0700    DEBUG    controller-runtime.controller    Successfully Reconciled    {"controller": "storageaccount", "request": "default/storageaccountsample777"}
2020-06-19T10:44:26.009-0700    INFO    controllers.StorageAccount    error during fetch from api server    {"Info Type": "ignorable error", "Component": "StorageAccount", "Instance": "default/storageaccountsample777"}
2020-06-19T10:44:26.010-0700    DEBUG    controller-runtime.controller    Successfully Reconciled    {"controller": "storageaccount", "request": "default/storageaccountsample777"}
```

I'm closing this as it looks like it doesn't repro anymore.

**Closed by matthchr** 2020-06-19 18:09 UTC
Labels: available-task, bug, storage, triaged
