### ISSUE TITLE
Bug: BackupVaultBackupInstance resource in comes to ready state even when the protection state is "

### ISSUE THREAD

**Issue by mayankagg9722** [Azure/azure-service-operator#3984] opened 2024-05-01 08:11 UTC
**Version of Azure Service Operator**

**Describe the bug**

**To Reproduce**
<Fill in the steps>

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by matthchr** [comment] 2024-05-01 17:14
Closing as this seems a duplicate of: https://github.com/Azure/azure-service-operator/issues/3985

**Closed by matthchr** 2024-05-01 17:14 UTC
