### ISSUE TITLE
Feature: Azure ad groups 

### ISSUE THREAD

**Issue by FernandoMiguel** [Azure/azure-service-operator#3541] opened 2023-11-12 02:23 UTC
We would love to be able to create Azure ad groups and manage their members via a k8s controller. 

Thanks

**Comment by matthchr** [comment] 2023-11-13 23:20
This is similar (possibly a duplicate of?): #2474

**Comment by matthchr** [comment] 2024-07-29 23:36
No change from above - we're interested in doing this but haven't gotten to it yet. Also putting this into 2.10.0 as #2474 was already there.

**Comment by matthchr** [comment] 2024-10-28 23:00
Closing this as a duplicate of #3459 (which itself might be a duplicate of #2474 but not going to close it as it has a good number of upvotes which signifies the interest in this topic).

**Closed by matthchr** 2024-10-28 23:00 UTC
Labels: new-feature, new-resource
