### ISSUE TITLE
Bug: Invalid cert-manager annotation on CRD

### ISSUE THREAD

**Issue by Desuuuu** [Azure/azure-service-operator#3057] opened 2023-06-08 17:08 UTC
**Version of Azure Service Operator**
v2.1.0

**Describe the bug**
When deploying to a namespace other than `azureserviceoperator-system`, the `cert-manager.io/inject-ca-from` annotation on CRDs contains the wrong namespace, causing webhook errors.

**To Reproduce**
* Deploy ASO to a namespace other than `azureserviceoperator-system` with CRD installation enabled
* Inspect the installed CRD resources
* The `cert-manager.io/inject-ca-from` annotation value is `azureserviceoperator-system/azureserviceoperator-serving-cert`

**Expected behavior**
The `cert-manager.io/inject-ca-from` annotation should reflect the namespace that ASO was installed in.

**Additional context**
The controller already tries to address this, but it is looking for a label named `cert-manager.io/inject-ca-from` instead of an annotation.

https://github.com/Azure/azure-service-operator/blob/3598bd628d55cb7ea47e4587e2fb1f4f5a9f33f3/v2/internal/crdmanagement/manager.go#L392-L400

**Comment by matthchr** [comment] 2023-06-08 17:12
doh, that's my bug. Easy fix I will send a PR.

**Comment by matthchr** [comment] 2023-06-08 17:29
The fix is in #3058. Thanks for the report and the debugging you did to root cause it!

**Closed** 2023-06-09 18:28 UTC
Labels: bug 🪲
