### ISSUE TITLE
Feature: Attach Azure Key Vault Policy to an existing Key Vault

### ISSUE THREAD

**Issue by danielkimuipath** [Azure/azure-service-operator#3697] opened 2024-01-10 01:02 UTC
Hi Team,

I noticed that Key Vault Policy is part of Key Vault Resource.
[This design](https://azure.github.io/azure-service-operator/reference/keyvault/v1api20230701/#keyvault.azure.com/v1api20230701.AccessPolicyEntry) supports when KV is managed by ASO in the beginning but it does not support for addding Azure Key Vault policies for exisitng Key Vault that are managed externally.

Looking at Terraform's example, it has its own KV access policy separately - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy. 

With this de-coupling from KV and KV policies, users can leave KV as it is and just manage the policy configuration within the KV independently.

Thanks!

**Comment by danielkimuipath** [comment] 2024-01-10 01:04
If you are using KV and handling KV access policy separately, how do you mange them with ASO usage? it would be great if you can share some expereiences of it.

**Comment by matthchr** [comment] 2024-01-22 23:48
It looks like this might be a duplicate of #2940. Will leave this open for now though until we can confirm and also have a more concrete answer to #2940 as to what we're planning to do.

**Comment by matthchr** [comment] 2024-07-29 23:43
Closing this as it is a duplicate of #2940.

**Closed by matthchr** 2024-07-29 23:43 UTC
Labels: new-feature
