### ISSUE TITLE
Become listed on Artifact Hub

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-service-operator#3718] opened 2024-01-19 16:36 UTC
**Describe the current behavior**
ASO is not discoverable on Artifact Hub

https://artifacthub.io/packages/search?ts_query_web=azure+service+operator&sort=relevance&page=1

**Describe the improvement**
Become listed on Artifact Hub to make it more discoverable for customers and show the available versions, configuration options etc.

Example of how I've set it up for KEDA: https://artifacthub.io/packages/helm/kedacore/keda

**Additional context**
I'm happy to contribute this.

**Comment by theunrepentantgeek** [comment] 2024-01-22 19:46
IIRC, Artifact Hub has a requirement that operators can't manage their own CRDs, they need to be deployed as YAML via Helm or similar. Our CRDs are far far too large to deploy that way - a side effect of supporting a growing selection of Azure Resources. [Helm stashes a copy of the CRDs, compressed, as a single secret or config-map (I forget which) and the maximum size of those is 2MB by default ... even though our CRDs compressed to 4% of their original size, we well exceed that size.

If we want to list on Artifact Hub, we need to address the CRD size in some way, possibly by sharding the operator into one per group.

**Comment by matthchr** [comment] 2024-01-23 00:01
See #2929 - the issue as @theunrepentantgeek called out is that ASO is actually too big. We've discussed sharding the operator CRDs before, and we _can_ do that but it's a bit of a pain. We've been holding out hope that OperatorHub will do something to help us out here but we admittedly we haven't been pushing them very hard on it.

As @theunrepentantgeek they forbid us managing our own CRDs which is the less secure but easier path that most users take.

**Comment by matthchr** [comment] 2024-01-23 00:01
I think that this is a duplicate of #1967 as well, though the links to KEDA would be useful to move over there as it's a nice reference.

**Comment by tomkerkhove** [comment] 2024-01-23 06:52
Let me reach out to Sergio and see if that rule still applies; maybe things have changed.

**Comment by tomkerkhove** [comment] 2024-01-24 10:09
It looks like @tegioz even opened the proposal himself: https://github.com/Azure/azure-service-operator/issues/1284.

There is no requirement to be listed on **Artifact Hub** and should be OK to do so, but don't confuse this with **OperatorHub** which might have other requirements (they are 2 different things)

**Comment by matthchr** [comment] 2024-03-04 23:41
I think you're right - we were confusing Artifact Hub and Operator Hub. I know that there _are_ restrictions on ASO on Operator Hub because of their model, but possibly Artifact Hub doesn't have those same restrictions.

If you're happy to contribute this @tomkerkhove we'd definitely accept it. If not, we'll look into doing this ourselves!

**Comment by tomkerkhove** [comment] 2024-03-05 07:37
I'm happy to pick this up

**Comment by matthchr** [comment] 2024-03-11 23:32
Closing as duplicate of #1284, that issue is older - we'll use it to track this. @tomkerkhove feel free to assign that issue to yourself if you want to tackle it. Otherwise we'll pick it up eventually. I've removed low-priority from it.

**Closed by matthchr** 2024-03-11 23:32 UTC
