### ISSUE TITLE
Request for best process to switch Azure accounts for a running ASO instance

### ISSUE THREAD

**Issue by jrwinsor** [Azure/azure-service-operator#2565] opened 2022-10-24 20:13 UTC
In deploying Azure Service Operator (V2) we mistakenly provided incorrect Azure account credentials, resulting in Azure services being provisioned in the wrong Azure account.

We wish to fix this and provision resources in the correct account, but ran into errors for already provisioned resources when simply changing the account credentials.  

I would ask if the process to switch this cleanly is to first, remove the provisioned resources, switch the account credentials, and finally, re-provision the ASO managed resources.

If there is a better process, I would be happy to hear it.

Thanks
Jim Winsor Dell Technologies.

**Comment by matthchr** [comment] 2022-10-24 21:24
> We wish to fix this and provision resources in the correct account, but ran into errors for already provisioned resources when simply changing the account credentials.

The errors that you hit are _probably_ resource specific. What I mean by that is that some resource types allow different entities in different subscriptions with the same name to coexist, while some do not. This means that technically you don't need to delete everything in the wrong subscription, you just need to delete the ones that aren't allowed to be recreated with the same name. This is probably things that have DNS entries derived from their names (SQL servers, etc). Things like VNETs, VMSS's, etc will likely be OK.

With that said, **we'd recommend** just deleting everything (can be done with `kubectl delete -f <>` assuming you've got the YAML of the resources you've created), then changing the ASO operator secret to point to the right subscription, and then recreating the resources. That way you don't end up getting billed for something you forgot about in the other subscription.

**Comment by matthchr** [comment] 2022-10-24 23:07
You'll also need to restart the azure-service-operator pod after you've updated the secret or it will still have the old values cached.

**Comment by jrwinsor** [comment] 2022-10-25 17:49
Thanks for the quick turnaround!

Jim Winsor
Software Dev Principal Engineer
Dell | Security Software Engineering
Office: 512-723-7131
Email: ***@***.******@***.***>

**Comment by matthchr** [comment] 2022-10-26 17:06
Closing this as it sounds like the issue is resolved. Please reopen if that is not the case.

**Closed by matthchr** 2022-10-26 17:06 UTC
Labels: question, needs-triage :mag:
