### ISSUE TITLE
Bug: MySQLUser v1alpha2 does support granting ALL privileges to a database

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1770] opened 2021-09-01 01:51 UTC
**Describe the bug**
`MySQLUser` resources at `v1alpha2` don't support granting `ALL` privileges. On `v1alpha1` this worked fine.

**To Reproduce**
Create a `MySQLServer` and `MySQLDatabase`, then deploy a user with a grant for all permissions on the database:
```
apiVersion: azure.microsoft.com/v1alpha2
kind: MySQLUser
metadata:
  name: myuser
  namespace: myns
spec:
  resourceGroup: myrg
  server: myserver
  username: myuser
  databaseRoles:
    mydb:
    - ALL
```

**Expected behavior**
The user is created and granted all privileges on the specified database.

**Additional context**
The user is created, but not granted any privileges on the database. If you change the privilege to `SELECT`, you can see that it correctly grants the user `SELECT` privilege on the database.

**Comment by babbageclunk** [comment] 2021-09-02 06:16
I can reproduce this by creating the db and the user at the same time - the user is created but has no permissions on the database because it doesn't exist, but we don't retry when it does. If I update the user to have SELECT on the database and then again to have ALL, they get all the permissions they should have.

I'll change it so if we can't find the database we try to reconcile again (with backoff so things don't go crazy).

**Comment by kyschouv** [comment] 2021-09-02 06:21
I had tried creating the user after the database already existed, and it wasn't granted anything on the database when I deployed with ALL. When I deployed a new user with SELECT instead, it worked.

**Comment by babbageclunk** [comment] 2021-09-06 05:26
It turns out there's no race here - we can grant permissions for a database that doesn't exist yet and it's fine. What happened was the first time the user was reconciled with ALL it would work, they'd get all of the privileges. The next time they were reconciled, we'd collect up all of the privileges they had in the DB, compare them to the privs from k8s, and issue a grant ALL (since ALL doesn't appear in the DB explicitly) and then a revoke for the individual privileges (since they weren't listed in the resource).

In the linked PR we special-case ALL and it works as expected.

**Comment by babbageclunk** [comment] 2021-09-09 05:43
Keeping this open until the fix is released since it was raised by a user - sorry @kyschouv!

**Comment by matthchr** [comment] 2022-06-10 18:28
This was fixed a while ago, and we dont have the same issue in ASOv2 as well. Closing

**Closed by matthchr** 2022-06-10 18:28 UTC
Labels: bug
