### ISSUE TITLE
Feature: Grant Database level Roles To Postgresqluser

### ISSUE THREAD

**Issue by EdYa** [Azure/azure-service-operator#1420] opened 2021-04-22 13:28 UTC
At the moment it seems not to be possible to provide database specific roles to a Postgresqluser. We are referencing the dbName(Instance name) in the chart, but it is only possible to grant roles on the Postgresql Server but not on the referenced database.

**Comment by matthchr** [comment] 2021-04-22 18:06
I think that this is a duplicate of #1346. (@babbageclunk do you agree?)

I'm closing this for now. If you agree that #1346 covers this feel free to comment there and/or thumbs-up it. If you don't agree, comment here and we can reopen this issue and clarify how it's different than #1346.

**Closed by matthchr** 2021-04-22 18:06 UTC
Labels: new-feature
