### ISSUE TITLE
Bug: tags, nodeLabels, and nodeTaints cannot be completely removed from ManagedCluster, ManagedClustersAgentPool

### ISSUE THREAD

**Issue by nojnhuh** [Azure/azure-service-operator#3522] opened 2023-11-06 22:34 UTC
**Version of Azure Service Operator**

665765256cc3cd2f9e1351690642c0ce834045fa, built from source

**Describe the bug**
When setting any of the `spec` fields `tags`, `nodeLabels`, and `nodeTaints` in ManagedClustersAgentPool to a non-null value, then to a null value, none of the corresponding configuration is reset in Azure. ManagedCluster `spec.tags` is also affected.

**To Reproduce**
- Create a ManagedCluster with at least one key/value pair in `spec.tags`
- After the Managed Cluster is Ready, remove all of `spec.tags`
- The ManagedCluster goes to Reconciling and then to Ready, but the tags still exist according to Azure

**Expected behavior**
All of the tags are deleted in Azure.

**Screenshots**

**Additional context**

**Comment by nojnhuh** [comment] 2023-11-06 22:36
related to #3367, #3407

**Comment by theunrepentantgeek** [comment] 2023-11-06 22:38
Is this not fixed by #3407? If it's not, we may have a bug in our generated code.

**Comment by matthchr** [comment] 2023-11-06 22:39
Yeah I was going to say, this should've been fixed by #3407. We should be able to reproduce with a test on our end though.

@nojnhuh what were you doing in the SDK to make this work previously? Were you setting it to `null` or to an empty collection?

**Comment by nojnhuh** [comment] 2023-11-06 22:53
I'm pretty sure I built everything from source right and I can see the changes from #3407 in my local copy.
 
CAPZ sets these to empty, non-nil values to delete all, so like `map[string]string{}` or `SliceType{}`.

**Comment by matthchr** [comment] 2023-11-07 17:17
We did some digging into this and determine that the issue is that AKS RP treats `null` the same as omission, so while our test ensures that we pass `null` it does not ensure that `null` actually does what we want (which is clear the value). We'll fix that.

There are two possible fixes:
1. Pass empty collection instead of null for these collections automatically.
2. Allow user specified empty collection to propagate to AKS RP.

We'll need to think a bit about which option makes the most sense.

**Closed** 2023-11-12 22:08 UTC
Labels: bug 🪲, high-priority, capz
