### ISSUE TITLE
Make linking role easier to managed identity

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-service-operator#2056] opened 2022-01-27 17:19 UTC
**Describe the current behavior**
Currently the Role CRD takes an AAD Object ID to apply to, but getting that from a managed identity requires creating the identity and viewing its status.

**Describe the improvement**
It could also take reference of some sort, although it can't use our existing reference infrastructure directly as that is for ARM IDs only

**Comment by sakthi-vetrivel** [comment] 2022-03-14 22:22
Goal to finish design in beta-1

**Comment by super-harsh** [comment] 2022-08-25 22:23
Closing, Duplicate of #2435

**Closed by super-harsh** 2022-08-25 22:23 UTC
Labels: task
