### ISSUE TITLE
Add support for ARC Extensions

### ISSUE THREAD

**Issue by theunrepentantgeek** [Azure/azure-service-operator#3124] opened 2023-07-05 22:15 UTC
Add support for the extension resource `Microsoft.KubernetesConfiguration/extensions`.

See https://learn.microsoft.com/en-us/azure/templates/microsoft.kubernetesconfiguration/extensions?pivots=deployment-language-arm-template for resource details.

**Comment by matthchr** [comment] 2023-07-12 23:06
I realized this is a duplicate of #2934

**Closed by matthchr** 2023-07-12 23:06 UTC
Labels: new-feature, new-resource
