### ISSUE TITLE
Update OperatorHub release.

### ISSUE THREAD

**Issue by kyschouv** [Azure/azure-service-operator#1414] opened 2021-04-20 19:54 UTC
We are using OperatorHub to deploy Azure Service Operator, but it seems that the last time a release was published to OperatorHub was August of 2020, despite multiple releases since then. Could you please publish releases to OperatorHub as well?

**Comment by matthchr** [comment] 2021-04-20 21:54
This is a duplicate of #1392 (see PR #1410).

**Closed by matthchr** 2021-04-20 21:54 UTC
Labels: task
